name: demo

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List files
        run: ls -la
