name: demo

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

job:
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: list files
        uses: ls      